"""empty message

Revision ID: 92b33ef46e77
Revises: ab6746340aca
Create Date: 2022-08-02 20:38:54.291230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b33ef46e77'
down_revision = 'ab6746340aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'creator_id')
    # ### end Alembic commands ###
