"""empty message

Revision ID: bd319bb9b983
Revises: 53565953526f
Create Date: 2022-10-14 11:40:40.893939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd319bb9b983'
down_revision = '53565953526f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_area',
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], )
    )
    op.create_table('file_category',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], )
    )
    op.create_foreign_key(None, 'file', 'user', ['creator_id'], ['id'])
    op.drop_column('file', 'area')
    op.drop_column('file', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('category', sa.VARCHAR(length=100), nullable=True))
    op.add_column('file', sa.Column('area', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_table('file_category')
    op.drop_table('file_area')
    op.drop_table('category')
    op.drop_table('area')
    # ### end Alembic commands ###
